# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    Drago_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

Drago_controller:
  ros__parameters:
    joints:
      - Waist_joint
      - Shoulder_joint
      - Elbow_joint
      - Wrist_1_joint
      - Wrist_2_joint
      - Effector_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true