# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    #gripper_controller:
    #  type: joint_trajectory_controller/JointTrajectoryController


    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

#gripper_controller:
#  ros__parameters:
#    joints:
#      - Left_Claw_joint
#      - Right_Claw_joint
#    command_interfaces:
#      - position
#    state_interfaces:
#      - position
#    allow_nonzero_velocity_at_trajectory_end: true

arm_controller:
  ros__parameters:
    joints:
      - Waist_joint
      - Shoulder_joint
      - Elbow_joint
      - Wrist_1_joint
      - Wrist_2_joint
      - Effector_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true